"""empty message

Revision ID: f430ac8217b8
Revises: b59418d33935
Create Date: 2026-02-16 21:51:31.870525

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "f430ac8217b8"
down_revision: Union[str, Sequence[str], None] = "b59418d33935"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "agent_runs",
        sa.Column(
            "workspace_scope",
            sa.String(length=50),
            server_default=sa.text("'session'"),
            nullable=False,
        ),
    )
    op.add_column("agent_runs", sa.Column("workspace_ref_id", sa.Uuid(), nullable=True))
    op.create_index(
        op.f("ix_agent_runs_workspace_ref_id"),
        "agent_runs",
        ["workspace_ref_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_runs_workspace_scope"),
        "agent_runs",
        ["workspace_scope"],
        unique=False,
    )
    op.add_column(
        "agent_scheduled_tasks", sa.Column("project_id", sa.Uuid(), nullable=True)
    )
    op.add_column(
        "agent_scheduled_tasks",
        sa.Column(
            "workspace_scope",
            sa.String(length=50),
            server_default=sa.text("'session'"),
            nullable=False,
        ),
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_project_id"),
        "agent_scheduled_tasks",
        ["project_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_scheduled_tasks_workspace_scope"),
        "agent_scheduled_tasks",
        ["workspace_scope"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "agent_scheduled_tasks",
        "projects",
        ["project_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.add_column(
        "agent_sessions",
        sa.Column(
            "workspace_scope",
            sa.String(length=50),
            server_default=sa.text("'session'"),
            nullable=False,
        ),
    )
    op.add_column(
        "agent_sessions", sa.Column("workspace_ref_id", sa.Uuid(), nullable=True)
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_ref_id"),
        "agent_sessions",
        ["workspace_ref_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_agent_sessions_workspace_scope"),
        "agent_sessions",
        ["workspace_scope"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_agent_sessions_workspace_scope"), table_name="agent_sessions"
    )
    op.drop_index(
        op.f("ix_agent_sessions_workspace_ref_id"), table_name="agent_sessions"
    )
    op.drop_column("agent_sessions", "workspace_ref_id")
    op.drop_column("agent_sessions", "workspace_scope")
    op.drop_constraint(
        "fk_agent_scheduled_tasks_project_id_projects",
        "agent_scheduled_tasks",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_workspace_scope"),
        table_name="agent_scheduled_tasks",
    )
    op.drop_index(
        op.f("ix_agent_scheduled_tasks_project_id"), table_name="agent_scheduled_tasks"
    )
    op.drop_column("agent_scheduled_tasks", "workspace_scope")
    op.drop_column("agent_scheduled_tasks", "project_id")
    op.drop_index(op.f("ix_agent_runs_workspace_scope"), table_name="agent_runs")
    op.drop_index(op.f("ix_agent_runs_workspace_ref_id"), table_name="agent_runs")
    op.drop_column("agent_runs", "workspace_ref_id")
    op.drop_column("agent_runs", "workspace_scope")
    # ### end Alembic commands ###
